<a href="https://colab.research.google.com/github/ogut77/BA/blob/main/PrepinPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

os2015=pd.read_csv('https://raw.githubusercontent.com/ogut77/BA/main/orders_south_2015.csv', encoding='latin-1')
os2016=pd.read_csv('https://raw.githubusercontent.com/ogut77/BA/main/orders_south_2016.csv', encoding='latin-1')
os2017=pd.read_csv('https://raw.githubusercontent.com/ogut77/BA/main/orders_south_2017.csv', encoding='latin-1')
os2018=pd.read_csv('https://raw.githubusercontent.com/ogut77/BA/main/orders_south_2018.csv', encoding='latin-1')

In [ ]:
pd.set_option('display.max_columns', 500)

In [2]:
print(os2015.columns)
print(os2016.columns)
print(os2017.columns)
print(os2018.columns)
print(os2015.shape)
print(os2016.shape)
print(os2017.shape)
print(os2018.shape)

Index(['Sales', 'Quantity', 'Profit', 'Discount', 'Region', 'State', 'Row ID',
       'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'Postal Code',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='object')
Index(['Sales', 'Quantity', 'Profit', 'Discount', 'Region', 'State', 'Row ID',
       'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'Postal Code',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='object')
Index(['Sales', 'Quantity', 'Profit', 'Discount', 'Region', 'State', 'Row ID',
       'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'Postal Code',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='object')
Index(['Sales', 'Quantity', 'Profit', 'Discount', 'Region', 'State', 'Row ID',
       'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'Postal Code',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='object')
(349, 21)
(340, 21)
(413, 21)
(518, 21)

In [3]:
frames = [os2015, os2016, os2017,os2018]

os = pd.concat(frames)
os

,Sales,Quantity,Profit,Discount,Region,State,Row ID,Order ID,Order Date,Ship Date,...,Customer ID,Customer Name,Segment,Country,City,Postal Code,Product ID,Category,Sub-Category,Product Name
0,503.960,4,131.0296,0.0,South,Louisiana,183,CA-2015-158274,11/19/2015 0:00,11/24/2015 0:00,...,RM-19675,Robert Marley,Home Office,United States,Monroe,71203,TEC-PH-10003273,Technology,Phones,AT&T TR1909W
1,149.950,5,41.9860,0.0,South,Louisiana,184,CA-2015-158274,11/19/2015 0:00,11/24/2015 0:00,...,RM-19675,Robert Marley,Home Office,United States,Monroe,71203,TEC-PH-10004896,Technology,Phones,Nokia Lumia 521 (T-Mobile)
2,29.000,2,7.2500,0.0,South,Louisiana,185,CA-2015-158274,11/19/2015 0:00,11/24/2015 0:00,...,RM-19675,Robert Marley,Home Office,United States,Monroe,71203,TEC-AC-10002345,Technology,Accessories,HP Standard 104 key PS/2 Keyboard
3,18.648,7,-12.4320,0.7,South,North Carolina,231,US-2015-156216,9/13/2015 0:00,9/17/2015 0:00,...,EA-14035,Erin Ashbrook,Corporate,United States,Charlotte,28205,OFF-BI-10001679,Office Supplies,Binders,GBC Instant Index System for Binding Systems
4,178.384,2,22.2980,0.2,South,Florida,315,CA-2015-167850,8/9/2015 0:00,8/16/2015 0:00,...,AG-10525,Andy Gerbode,Corporate,United States,Saint Petersburg,33710,TEC-PH-10002398,Technology,Phones,AT&T 1070 Corded Phone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,194.848,4,12.1780,0.2,South,North Carolina,9808,CA-2018-107209,7/27/2018 0:00,8/1/2018 0:00,...,JW-15955,Joni Wasserman,Consumer,United States,Raleigh,27604,FUR-CH-10001146,Furniture,Chairs,"Global Value Mid-Back Manager's Chair, Gray"
514,242.352,3,15.1470,0.2,South,North Carolina,9830,US-2018-152842,7/16/2018 0:00,7/23/2018 0:00,...,NF-18385,Natalie Fritzler,Consumer,United States,Charlotte,28205,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray"
515,18.000,1,3.2400,0.0,South,Kentucky,9961,CA-2018-141446,9/16/2018 0:00,9/18/2018 0:00,...,CL-12700,Craig Leslie,Home Office,United States,Florence,41042,TEC-AC-10002305,Technology,Accessories,KeyTronic E03601U1 - Keyboard - Beige
516,79.990,1,28.7964,0.0,South,Georgia,9988,CA-2018-163629,11/17/2018 0:00,11/21/2018 0:00,...,RA-19885,Ruben Ausman,Corporate,United States,Athens,30605,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...
517,206.100,5,55.6470,0.0,South,Georgia,9989,CA-2018-163629,11/17/2018 0:00,11/21/2018 0:00,...,RA-19885,Ruben Ausman,Corporate,United States,Athens,30605,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone

In [4]:
os['Order Date'] = pd.to_datetime(os['Order Date'])
os['Ship Date'] = pd.to_datetime(os['Ship Date'])
os

,Sales,Quantity,Profit,Discount,Region,State,Row ID,Order ID,Order Date,Ship Date,...,Customer ID,Customer Name,Segment,Country,City,Postal Code,Product ID,Category,Sub-Category,Product Name
0,503.960,4,131.0296,0.0,South,Louisiana,183,CA-2015-158274,2015-11-19,2015-11-24,...,RM-19675,Robert Marley,Home Office,United States,Monroe,71203,TEC-PH-10003273,Technology,Phones,AT&T TR1909W
1,149.950,5,41.9860,0.0,South,Louisiana,184,CA-2015-158274,2015-11-19,2015-11-24,...,RM-19675,Robert Marley,Home Office,United States,Monroe,71203,TEC-PH-10004896,Technology,Phones,Nokia Lumia 521 (T-Mobile)
2,29.000,2,7.2500,0.0,South,Louisiana,185,CA-2015-158274,2015-11-19,2015-11-24,...,RM-19675,Robert Marley,Home Office,United States,Monroe,71203,TEC-AC-10002345,Technology,Accessories,HP Standard 104 key PS/2 Keyboard
3,18.648,7,-12.4320,0.7,South,North Carolina,231,US-2015-156216,2015-09-13,2015-09-17,...,EA-14035,Erin Ashbrook,Corporate,United States,Charlotte,28205,OFF-BI-10001679,Office Supplies,Binders,GBC Instant Index System for Binding Systems
4,178.384,2,22.2980,0.2,South,Florida,315,CA-2015-167850,2015-08-09,2015-08-16,...,AG-10525,Andy Gerbode,Corporate,United States,Saint Petersburg,33710,TEC-PH-10002398,Technology,Phones,AT&T 1070 Corded Phone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,194.848,4,12.1780,0.2,South,North Carolina,9808,CA-2018-107209,2018-07-27,2018-08-01,...,JW-15955,Joni Wasserman,Consumer,United States,Raleigh,27604,FUR-CH-10001146,Furniture,Chairs,"Global Value Mid-Back Manager's Chair, Gray"
514,242.352,3,15.1470,0.2,South,North Carolina,9830,US-2018-152842,2018-07-16,2018-07-23,...,NF-18385,Natalie Fritzler,Consumer,United States,Charlotte,28205,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray"
515,18.000,1,3.2400,0.0,South,Kentucky,9961,CA-2018-141446,2018-09-16,2018-09-18,...,CL-12700,Craig Leslie,Home Office,United States,Florence,41042,TEC-AC-10002305,Technology,Accessories,KeyTronic E03601U1 - Keyboard - Beige
516,79.990,1,28.7964,0.0,South,Georgia,9988,CA-2018-163629,2018-11-17,2018-11-21,...,RA-19885,Ruben Ausman,Corporate,United States,Athens,30605,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...
517,206.100,5,55.6470,0.0,South,Georgia,9989,CA-2018-163629,2018-11-17,2018-11-21,...,RA-19885,Ruben Ausman,Corporate,United States,Athens,30605,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone

In [5]:
oc=pd.read_csv('https://raw.githubusercontent.com/ogut77/BA/main/Orders_Central.csv', encoding='latin-1')

In [6]:
print(oc.columns)
print(len(oc.columns))
oc.head()

Index(['Row ID', 'Order ID', 'Ship Mode', 'Customer ID', 'Customer Name',
       'Segment', 'Country', 'City', 'State', 'Postal Code', 'Product ID',
       'Category', 'Sub-Category', 'Product', 'Sales', 'Quantity', 'Profit',
       'Order Year', 'Order Month', 'Order Day', 'Ship Year', 'Ship Month',
       'Ship Day', 'Discounts'],
      dtype='object')
24

,Row ID,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,...,Sales,Quantity,Profit,Order Year,Order Month,Order Day,Ship Year,Ship Month,Ship Day,Discounts
0,15,US-2016-118983,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106,...,68.810,5,-123.8580,2016,11,22,2016,11,26,0.8
1,16,US-2016-118983,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106,...,2.544,3,-3.8160,2016,11,22,2016,11,26,0.8
2,17,CA-2015-105893,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,Wisconsin,53711,...,665.880,6,13.3176,2015,11,11,2015,11,18,None
3,22,CA-2017-137330,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025,...,19.460,7,5.0596,2017,12,9,2017,12,13,None
4,23,CA-2017-137330,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025,...,60.340,7,15.6884,2017,12,9,2017,12,13,None

In [7]:
dif1 = os.columns.difference(oc.columns)
print(dif1)
dif2 = oc.columns.difference(os.columns)
print(dif2)

Index(['Discount', 'Order Date', 'Product Name', 'Region', 'Ship Date'], dtype='object')
Index(['Discounts', 'Order Day', 'Order Month', 'Order Year', 'Product',
       'Ship Day', 'Ship Month', 'Ship Year'],
      dtype='object')

In [8]:
oc = oc.rename(columns={'Discounts': 'Discount'})
oc = oc.rename(columns={'Product': 'Product Name'})
dif2 = oc.columns.difference(os.columns)
print(dif2)

Index(['Order Day', 'Order Month', 'Order Year', 'Ship Day', 'Ship Month',
       'Ship Year'],
      dtype='object')

In [9]:
from datetime import datetime

# Create a datetime object
oc['Order Date'] = pd.to_datetime(dict(month=oc['Order Month'],day=oc['Order Day'],year=oc['Order Year']))
oc['Ship Date']= pd.to_datetime(dict(month=oc['Ship Month'],day=oc['Ship Day'],year=oc['Ship Year']))
oc

,Row ID,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,...,Profit,Order Year,Order Month,Order Day,Ship Year,Ship Month,Ship Day,Discount,Order Date,Ship Date
0,15,US-2016-118983,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106,...,-123.8580,2016,11,22,2016,11,26,0.8,2016-11-22,2016-11-26
1,16,US-2016-118983,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106,...,-3.8160,2016,11,22,2016,11,26,0.8,2016-11-22,2016-11-26
2,17,CA-2015-105893,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,Wisconsin,53711,...,13.3176,2015,11,11,2015,11,18,None,2015-11-11,2015-11-18
3,22,CA-2017-137330,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025,...,5.0596,2017,12,9,2017,12,13,None,2017-12-09,2017-12-13
4,23,CA-2017-137330,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025,...,15.6884,2017,12,9,2017,12,13,None,2017-12-09,2017-12-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2318,9962,CA-2016-168088,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,Texas,77041,...,23.7742,2016,3,19,2016,3,22,0.2,2016-03-19,2016-03-22
2319,9963,CA-2016-168088,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,Texas,77041,...,-67.6704,2016,3,19,2016,3,22,0.32,2016-03-19,2016-03-22
2320,9973,CA-2017-130225,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Houston,Texas,77041,...,33.6042,2017,9,11,2017,9,17,0.2,2017-09-11,2017-09-17
2321,9983,US-2017-157728,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,Michigan,49505,...,16.7132,2017,9,22,2017,9,28,None,2017-09-22,2017-09-28
2322,9984,US-2017-157728,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,Michigan,49505,...,27.4344,2017,9,22,2017,9,28,None,2017-09-22,2017-09-28

In [15]:
oc['Discount'] = oc['Discount'].replace({'None':0}, regex=True)
oc['Discount']

0        0.8
1        0.8
2          0
3          0
4          0
        ...
2318     0.2
2319    0.32
2320     0.2
2321       0
2322       0
Name: Discount, Length: 2323, dtype: object

In [10]:
oc.columns

Index(['Row ID', 'Order ID', 'Ship Mode', 'Customer ID', 'Customer Name',
       'Segment', 'Country', 'City', 'State', 'Postal Code', 'Product ID',
       'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity',
       'Profit', 'Order Year', 'Order Month', 'Order Day', 'Ship Year',
       'Ship Month', 'Ship Day', 'Discount', 'Order Date', 'Ship Date'],
      dtype='object')

In [11]:
oc['Region']='Central'

In [12]:
oe=pd.read_excel('https://raw.githubusercontent.com/ogut77/BA/main/Orders_East.xlsx')
oe.head()

,Category,City,Country,Customer ID,Customer Name,Discount,Order Date,Order ID,Postal Code,Product ID,...,Profit,Quantity,Region,Row ID,Segment,Ship Date,Ship Mode,State,Sub-Category,Sales
0,Furniture,Philadelphia,United States,SF-20065,Sandra Flanagan,0.3,2018-07-16,US-2018-156909,19140.0,FUR-CH-10002774,...,-1.0196,2.0,East,24.0,Consumer,2018-07-18,Second Class,Pennsylvania,Chairs,USD71.37
1,Office Supplies,Philadelphia,United States,TB-21520,Tracy Blumstein,0.7,2016-09-17,US-2016-150630,19140.0,OFF-BI-10000474,...,-7.0532,2.0,East,29.0,Consumer,2016-09-21,Standard Class,Pennsylvania,Binders,USD9.61
2,Office Supplies,Philadelphia,United States,TB-21520,Tracy Blumstein,0.7,2016-09-17,US-2016-150630,19140.0,OFF-BI-10001525,...,-5.7150,6.0,East,33.0,Consumer,2016-09-21,Standard Class,Pennsylvania,Binders,USD6.85
3,Office Supplies,Philadelphia,United States,FH-14365,Fred Hopkins,0.7,2018-07-06,US-2018-124303,19120.0,OFF-BI-10000343,...,-2.2586,2.0,East,199.0,Corporate,2018-07-13,Standard Class,Pennsylvania,Binders,USD2.94
4,Technology,Medina,United States,VW-21775,Victoria Wilson,0.7,2016-01-02,CA-2016-146262,44256.0,TEC-MA-10000864,...,-950.4000,9.0,East,216.0,Corporate,2016-01-09,Standard Class,Ohio,Machines,USD1188

In [13]:
oe['Sales'] = oe['Sales'].replace({'USD':''}, regex=True)
oe['Sales']

0        71.37
1         9.61
2         6.85
3         2.94
4         1188
         ...
2841     40.20
2842    735.98
2843     22.75
2844      31.5
2845     55.60
Name: Sales, Length: 2846, dtype: object

In [14]:
oe.columns
dif3 = oe.columns.difference(os.columns)
print(dif3)

Index([], dtype='object')

In [16]:
ow=pd.read_csv('https://raw.githubusercontent.com/ogut77/BA/main/Orders_West.csv', encoding='latin-1')
ow.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Right_Region,Right_Product ID,Right_Category,Right_Sub-Category,Right_Product Name,Right_Sales,Right_Quantity,Right_Discount,Right_Profit,State
0,3836,CA-2015-100363,2015-04-08 00:00:00,2015-04-15 00:00:00,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,2.368,2,0.2,0.8288,AZ
1,3837,CA-2015-100363,2015-04-08 00:00:00,2015-04-15 00:00:00,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,2.368,2,0.2,0.8288,AZ
2,3836,CA-2015-100363,2015-04-08 00:00:00,2015-04-15 00:00:00,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-PA-10004733,Office Supplies,Paper,Things To Do Today Spiral Book,19.008,3,0.2,6.8904,AZ
3,3837,CA-2015-100363,2015-04-08 00:00:00,2015-04-15 00:00:00,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-PA-10004733,Office Supplies,Paper,Things To Do Today Spiral Book,19.008,3,0.2,6.8904,AZ
4,4565,CA-2015-101175,2015-12-09 00:00:00,2015-12-14 00:00:00,Standard Class,DM-12955,Dario Medina,Corporate,United States,Mesa,...,West,OFF-ST-10004950,Office Supplies,Storage,Acco Perma 3000 Stacking Storage Drawers,100.704,6,0.2,-1.2588,AZ

In [17]:
dif3 = ow.columns.difference(os.columns)
print(dif3)

Index(['Right_Category', 'Right_City', 'Right_Country', 'Right_Customer ID',
       'Right_Customer Name', 'Right_Discount', 'Right_Order Date',
       'Right_Postal Code', 'Right_Product ID', 'Right_Product Name',
       'Right_Profit', 'Right_Quantity', 'Right_Region', 'Right_Row ID',
       'Right_Sales', 'Right_Segment', 'Right_Ship Date', 'Right_Ship Mode',
       'Right_State2', 'Right_Sub-Category'],
      dtype='object')

In [18]:
ow.drop(['Right_Category', 'Right_City', 'Right_Country', 'Right_Customer ID',
       'Right_Customer Name', 'Right_Discount', 'Right_Order Date',
       'Right_Postal Code', 'Right_Product ID', 'Right_Product Name',
       'Right_Profit', 'Right_Quantity', 'Right_Region', 'Right_Row ID',
       'Right_Sales', 'Right_Segment', 'Right_Ship Date', 'Right_Ship Mode',
       'State', 'Right_Sub-Category'],axis=1,inplace=True)

In [19]:
ow.columns
dif3 = ow.columns.difference(os.columns)
print(dif3)

Index(['Right_State2'], dtype='object')

In [20]:
ow.rename(columns = {'Right_State2':'State'}, inplace = True)
ow

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,State
0,3836,CA-2015-100363,2015-04-08 00:00:00,2015-04-15 00:00:00,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,2.368,2,0.2,0.8288,Arizona
1,3837,CA-2015-100363,2015-04-08 00:00:00,2015-04-15 00:00:00,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-PA-10004733,Office Supplies,Paper,Things To Do Today Spiral Book,19.008,3,0.2,6.8904,Arizona
2,3836,CA-2015-100363,2015-04-08 00:00:00,2015-04-15 00:00:00,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,2.368,2,0.2,0.8288,Arizona
3,3837,CA-2015-100363,2015-04-08 00:00:00,2015-04-15 00:00:00,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-PA-10004733,Office Supplies,Paper,Things To Do Today Spiral Book,19.008,3,0.2,6.8904,Arizona
4,4565,CA-2015-101175,2015-12-09 00:00:00,2015-12-14 00:00:00,Standard Class,DM-12955,Dario Medina,Corporate,United States,Mesa,...,West,OFF-ST-10004950,Office Supplies,Storage,Acco Perma 3000 Stacking Storage Drawers,100.704,6,0.2,-1.2588,Arizona
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9548,6234,US-2018-142188,2018-09-11 00:00:00,2018-09-11 00:00:00,Same Day,JF-15415,Jennifer Ferguson,Consumer,United States,Seattle,...,West,OFF-PA-10004101,Office Supplies,Paper,Xerox 1894,71.280,11,0.0,34.2144,Washington
9549,6235,US-2018-142188,2018-09-11 00:00:00,2018-09-11 00:00:00,Same Day,JF-15415,Jennifer Ferguson,Consumer,United States,Seattle,...,West,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,1471.960,5,0.2,459.9875,Washington
9550,6236,US-2018-142188,2018-09-11 00:00:00,2018-09-11 00:00:00,Same Day,JF-15415,Jennifer Ferguson,Consumer,United States,Seattle,...,West,TEC-PH-10000127,Technology,Phones,iOttie XL Car Mount,79.960,5,0.2,-17.9910,Washington
9551,8294,US-2018-168802,2018-11-03 00:00:00,2018-11-07 00:00:00,Standard Class,JO-15145,Jack O'Briant,Corporate,United States,Seattle,...,West,OFF-BI-10002393,Office Supplies,Binders,Binder Posts,18.368,4,0.2,5.9696,Washington
9552,5870,CA-2017-152247,2017-11-07 00:00:00,2017-11-12 00:00:00,Standard Class,MA-17995,Michelle Arnett,Home Office,United States,Cheyenne,...,West,FUR-CH-10001215,Furniture,Chairs,Global Troy Executive Leather Low-Back Tilter,1603.136,4,0.2,100.1960,Wyoming

In [21]:
ow['Order Date'] = pd.to_datetime(ow['Order Date'])
ow['Ship Date'] = pd.to_datetime(ow['Ship Date'])
ow

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,State
0,3836,CA-2015-100363,2015-04-08,2015-04-15,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,2.368,2,0.2,0.8288,Arizona
1,3837,CA-2015-100363,2015-04-08,2015-04-15,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-PA-10004733,Office Supplies,Paper,Things To Do Today Spiral Book,19.008,3,0.2,6.8904,Arizona
2,3836,CA-2015-100363,2015-04-08,2015-04-15,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,2.368,2,0.2,0.8288,Arizona
3,3837,CA-2015-100363,2015-04-08,2015-04-15,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,West,OFF-PA-10004733,Office Supplies,Paper,Things To Do Today Spiral Book,19.008,3,0.2,6.8904,Arizona
4,4565,CA-2015-101175,2015-12-09,2015-12-14,Standard Class,DM-12955,Dario Medina,Corporate,United States,Mesa,...,West,OFF-ST-10004950,Office Supplies,Storage,Acco Perma 3000 Stacking Storage Drawers,100.704,6,0.2,-1.2588,Arizona
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9548,6234,US-2018-142188,2018-09-11,2018-09-11,Same Day,JF-15415,Jennifer Ferguson,Consumer,United States,Seattle,...,West,OFF-PA-10004101,Office Supplies,Paper,Xerox 1894,71.280,11,0.0,34.2144,Washington
9549,6235,US-2018-142188,2018-09-11,2018-09-11,Same Day,JF-15415,Jennifer Ferguson,Consumer,United States,Seattle,...,West,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,1471.960,5,0.2,459.9875,Washington
9550,6236,US-2018-142188,2018-09-11,2018-09-11,Same Day,JF-15415,Jennifer Ferguson,Consumer,United States,Seattle,...,West,TEC-PH-10000127,Technology,Phones,iOttie XL Car Mount,79.960,5,0.2,-17.9910,Washington
9551,8294,US-2018-168802,2018-11-03,2018-11-07,Standard Class,JO-15145,Jack O'Briant,Corporate,United States,Seattle,...,West,OFF-BI-10002393,Office Supplies,Binders,Binder Posts,18.368,4,0.2,5.9696,Washington
9552,5870,CA-2017-152247,2017-11-07,2017-11-12,Standard Class,MA-17995,Michelle Arnett,Home Office,United States,Cheyenne,...,West,FUR-CH-10001215,Furniture,Chairs,Global Troy Executive Leather Low-Back Tilter,1603.136,4,0.2,100.1960,Wyoming

In [22]:
os2=os[['Sales', 'Quantity', 'Profit', 'Discount', 'Region', 'State','Row ID',
       'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'Postal Code',
       'Product ID', 'Category', 'Sub-Category', 'Product Name']]
ow2=ow[['Sales', 'Quantity', 'Profit', 'Discount', 'Region', 'State','Row ID',
       'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'Postal Code',
       'Product ID', 'Category', 'Sub-Category', 'Product Name']]
oe2=oe[['Sales', 'Quantity', 'Profit', 'Discount', 'Region', 'State','Row ID',
       'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'Postal Code',
       'Product ID', 'Category', 'Sub-Category', 'Product Name']]
oc2=oc[['Sales', 'Quantity', 'Profit', 'Discount', 'Region', 'State','Row ID',
       'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'Postal Code',
       'Product ID', 'Category', 'Sub-Category', 'Product Name']]

In [23]:

frames = [os2, oc2, oe2,ow2]

oall = pd.concat(frames)

oall

,Sales,Quantity,Profit,Discount,Region,State,Row ID,Order ID,Order Date,Ship Date,...,Customer ID,Customer Name,Segment,Country,City,Postal Code,Product ID,Category,Sub-Category,Product Name
0,503.96,4.0,131.0296,0.0,South,Louisiana,183.0,CA-2015-158274,2015-11-19,2015-11-24,...,RM-19675,Robert Marley,Home Office,United States,Monroe,71203.0,TEC-PH-10003273,Technology,Phones,AT&T TR1909W
1,149.95,5.0,41.9860,0.0,South,Louisiana,184.0,CA-2015-158274,2015-11-19,2015-11-24,...,RM-19675,Robert Marley,Home Office,United States,Monroe,71203.0,TEC-PH-10004896,Technology,Phones,Nokia Lumia 521 (T-Mobile)
2,29.0,2.0,7.2500,0.0,South,Louisiana,185.0,CA-2015-158274,2015-11-19,2015-11-24,...,RM-19675,Robert Marley,Home Office,United States,Monroe,71203.0,TEC-AC-10002345,Technology,Accessories,HP Standard 104 key PS/2 Keyboard
3,18.648,7.0,-12.4320,0.7,South,North Carolina,231.0,US-2015-156216,2015-09-13,2015-09-17,...,EA-14035,Erin Ashbrook,Corporate,United States,Charlotte,28205.0,OFF-BI-10001679,Office Supplies,Binders,GBC Instant Index System for Binding Systems
4,178.384,2.0,22.2980,0.2,South,Florida,315.0,CA-2015-167850,2015-08-09,2015-08-16,...,AG-10525,Andy Gerbode,Corporate,United States,Saint Petersburg,33710.0,TEC-PH-10002398,Technology,Phones,AT&T 1070 Corded Phone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9548,71.28,11.0,34.2144,0.0,West,Washington,6234.0,US-2018-142188,2018-09-11,2018-09-11,...,JF-15415,Jennifer Ferguson,Consumer,United States,Seattle,98105.0,OFF-PA-10004101,Office Supplies,Paper,Xerox 1894
9549,1471.96,5.0,459.9875,0.2,West,Washington,6235.0,US-2018-142188,2018-09-11,2018-09-11,...,JF-15415,Jennifer Ferguson,Consumer,United States,Seattle,98105.0,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System
9550,79.96,5.0,-17.9910,0.2,West,Washington,6236.0,US-2018-142188,2018-09-11,2018-09-11,...,JF-15415,Jennifer Ferguson,Consumer,United States,Seattle,98105.0,TEC-PH-10000127,Technology,Phones,iOttie XL Car Mount
9551,18.368,4.0,5.9696,0.2,West,Washington,8294.0,US-2018-168802,2018-11-03,2018-11-07,...,JO-15145,Jack O'Briant,Corporate,United States,Seattle,98103.0,OFF-BI-10002393,Office Supplies,Binders,Binder Posts
9552,1603.136,4.0,100.1960,0.2,West,Wyoming,5870.0,CA-2017-152247,2017-11-07,2017-11-12,...,MA-17995,Michelle Arnett,Home Office,United States,Cheyenne,82001.0,FUR-CH-10001215,Furniture,Chairs,Global Troy Executive Leather Low-Back Tilter